consumerKey = "vQziJUNbc6p31AFnuAFHJV8Ns"
consumerSecret = "O016CkMyRJR5q3gS3BzNRzxP1YJbcB3U65trzqO6yvGpDcnBb0"
accessToken = "1015106539604959232-SWhTBBbJanBEQWxR4ZkWMOmY0JkihM"
accessTokenSecret = "7R1S67et9bY89oauXJb49PDlXjAkupGNytRoLEmsLA1t3"
